// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDghy0CzdGxgWLDujsVC_zNcQeW5FjUAGU',
    appId: '1:1001031051231:web:f72ace71b8269cf4fe866a',
    messagingSenderId: '1001031051231',
    projectId: 'its-urgent',
    authDomain: 'its-urgent.firebaseapp.com',
    storageBucket: 'its-urgent.appspot.com',
    measurementId: 'G-Z4S4K2QSCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9kVN3eBUZFK8fK_DKWq2rpg5x8wdKKvM',
    appId: '1:1001031051231:android:92418fb25d815707fe866a',
    messagingSenderId: '1001031051231',
    projectId: 'its-urgent',
    storageBucket: 'its-urgent.appspot.com',
  );
}
